version: '3'
services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - "5000:5000"
    depends_on:
      - database
  database:
    build: database
    ports:
      - "5432:5432"
